name: Register the model for the given pipeline branch

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

# on:
#   pull_request:
#     types:
#       - closed
#     branches:
#       - "main"

permissions: write-all

jobs:

  Register-New-Model-Dev:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install packages to register model
      run: |
        pip install --upgrade pip
        pip install gto
        
    - name: Register Model
      run: |

        # --- IGNORE BRANCH NAME FOR NOW ---
        # REGISTER_MODEL_NAME=$(echo ${{ github.event.pull_request.head.ref }} | awk -F"-" '{print $1}')
        
        REGISTER_MODEL_NAME=$(echo ${{github.ref_name}} | awk -F"-" '{print $1}')

        git config user.name "Github-Bot"
        git config user.email "Github-Bot@no-reply.com"
        git show
        git remote -v show
        echo $GITHUB_REF
        git log -n 2
        
        gto -v register regression
        git push origin regression@v0.0.1

        # --- IGNORE SUBSEQUENT STEPS ---
        # gto assign regression --stage dev
        # gto show
