name: Register the model for the given pipeline branch

on:
  push:
    branches:
      - "master"

# on:
#   pull_request:
#     types:
#       - closed
#     branches:
#       - "master"

permissions: write-all

jobs:

  Register-New-Model-Dev:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install packages to register model
      run: |
        pip install --upgrade pip
        pip install gto
        
    - name: Register Model
      run: |

        # REGISTER_MODEL_NAME=$(echo ${{ github.event.pull_request.head.ref }} | awk -F"-" '{print $1}')
        REGISTER_MODEL_NAME=$(echo ${{github.ref_name}} | awk -F"-" '{print $1}')

        git config user.name "Github-Bot"
        git config user.email "Github-Bot@no-reply.com"

        # git tag model@v0.0.1
        # git push origin model@v0.0.1

        # gto register test --repo https://github.com/Hestia-Homes/ML/
        # echo "chicken" >> test.md

        gto register ${REGISTER_MODEL_NAME}
        # gto assign regression --stage dev
        # gto show
